default: develop

@list:
	just --list --unsorted

alias help := list

develop:
	#!/usr/bin/env bash
	set -euo pipefail

	watchexec --exts md --postpone --quiet --clear -- just md2html &
	watchexec --watch md2html --quiet --clear -- just md2html &
	watchexec --exts go,html,css,js --ignore 'md2html/*' --debounce 200ms --restart -- HTTP_HOST=interrato.dev go run . &

	wait

md2html:
	#!/usr/bin/env bash
	set -euo pipefail

	find . -name "*.md" -printf '%P\0' |
	while IFS= read -r -d '' file; do
		go run ./md2html "$file"
	done
